/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye6200.view;
import edu.neu.csye6200.model.Classroom;
import edu.neu.csye6200.model.DayCare;
import edu.neu.csye6200.model.Group;
import edu.neu.csye6200.model.Student;
import edu.neu.csye6200.model.Teacher;
import edu.neu.csye6200.util.GroupRules;
import edu.neu.csye6200.util.UiUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varun
 */
public class ClassRoomsView extends javax.swing.JPanel {

    List<Object> classRooms = new ArrayList<>();
    DefaultTableModel groupDtm;
    DefaultTableModel studentDtm;
    DayCare daycare;
    int selectedGroupIndex;
    int selectedClassIndex;
    /**
     * Creates new form ClassRoomsView
     */
    public ClassRoomsView(DayCare daycare) {
        this.daycare = daycare;
        selectedGroupIndex = -1;
        selectedClassIndex = -1;
        initComponents();
        postInit(daycare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        teacherHeadingLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        selectClassroomPanel = new javax.swing.JPanel();
        totalCount = new javax.swing.JLabel();
        addTeacherButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        classRoomSelect = new javax.swing.JComboBox<>();
        selectGroupPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupsTable = new javax.swing.JTable();
        groupsLabel = new javax.swing.JLabel();
        addGroupButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        groupLimitLabel = new javax.swing.JLabel();
        groupInfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        notePrefix = new javax.swing.JLabel();
        noteValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addStudentToGroupButton = new javax.swing.JButton();
        teacherLabel = new javax.swing.JLabel();
        teacherValueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        teacherHeadingLabel.setFont(new java.awt.Font("PT Sans", 3, 24)); // NOI18N
        teacherHeadingLabel.setText("C L A S S R O O M S");

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectClassroomPanel.setBackground(new java.awt.Color(255, 255, 255));

        addTeacherButton.setText("+ Add");
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT A CLASSROOM:");

        classRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classRoomSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoomSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectClassroomPanelLayout = new javax.swing.GroupLayout(selectClassroomPanel);
        selectClassroomPanel.setLayout(selectClassroomPanelLayout);
        selectClassroomPanelLayout.setHorizontalGroup(
            selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectClassroomPanelLayout.createSequentialGroup()
                .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(classRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(totalCount)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        selectClassroomPanelLayout.setVerticalGroup(
            selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTeacherButton))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(totalCount)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        selectGroupPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        groupsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        groupsTable.setColumnSelectionAllowed(true);
        groupsTable.getTableHeader().setReorderingAllowed(false);
        groupsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(groupsTable);
        groupsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        groupsLabel.setText("Groups:");

        addGroupButton.setText("+ Add");
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Group limit for this class: ");

        javax.swing.GroupLayout selectGroupPanelLayout = new javax.swing.GroupLayout(selectGroupPanel);
        selectGroupPanel.setLayout(selectGroupPanelLayout);
        selectGroupPanelLayout.setHorizontalGroup(
            selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(selectGroupPanelLayout.createSequentialGroup()
                        .addComponent(groupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(addGroupButton))
                    .addGroup(selectGroupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        selectGroupPanelLayout.setVerticalGroup(
            selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupsLabel)
                    .addComponent(addGroupButton))
                .addGap(18, 18, 18)
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(groupLimitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        groupInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Age", "GPA"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        notePrefix.setForeground(new java.awt.Color(255, 51, 51));
        notePrefix.setText("Note: Maximum number of students allowed:");

        noteValue.setText("-1");

        jLabel2.setText("Students");

        addStudentToGroupButton.setText("+ Add");
        addStudentToGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToGroupButtonActionPerformed(evt);
            }
        });

        teacherLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(255, 51, 51));
        teacherLabel.setText("Teacher: ");

        teacherValueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        javax.swing.GroupLayout groupInfoPanelLayout = new javax.swing.GroupLayout(groupInfoPanel);
        groupInfoPanel.setLayout(groupInfoPanelLayout);
        groupInfoPanelLayout.setHorizontalGroup(
            groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupInfoPanelLayout.createSequentialGroup()
                .addGroup(groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(groupInfoPanelLayout.createSequentialGroup()
                        .addComponent(teacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addStudentToGroupButton))
                    .addGroup(groupInfoPanelLayout.createSequentialGroup()
                        .addGroup(groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupInfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(notePrefix)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noteValue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        groupInfoPanelLayout.setVerticalGroup(
            groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudentToGroupButton)
                    .addComponent(teacherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(teacherValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notePrefix)
                    .addComponent(noteValue))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectClassroomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectClassroomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(473, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed
        AddClassRoomDialog addClass = new AddClassRoomDialog(daycare, this);
        addClass.setLocationRelativeTo(null);
        addClass.setVisible(true);
    }//GEN-LAST:event_addTeacherButtonActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        AddGroupDialog ag = new AddGroupDialog(daycare, classRoomSelect.getSelectedIndex(), this);
        ag.setLocationRelativeTo(null);
        ag.setVisible(true);
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void classRoomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoomSelectActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String name = (String)cb.getSelectedItem();
       
        int index = cb.getSelectedIndex();
        if(index > -1){
            cb.setSelectedIndex(cb.getSelectedIndex());
            populateGroupTable();
            selectGroupPanel.setVisible(true);
            cb.setSelectedItem(name);
            selectedClassIndex = index;
            groupLimitLabel.setText(""+daycare.getClassRoomsList().get(cb.getSelectedIndex()).getMaxGroup());
            
        }
        checkMaxLimitForGroup();
        checkMaxLimitForGroupAddition();
        
    }//GEN-LAST:event_classRoomSelectActionPerformed

    private void groupsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsTableMouseClicked
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            String s=source.getModel().getValueAt(row, 0)+"";
            groupInfoPanel.setVisible(true);
            selectedGroupIndex = row;
            noteValue.setText(""+daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex()).getGroups().get(row).getGroupSize());
            checkMaxLimitForGroup();
            populateStudentTable();
            setTeacherName();
    }//GEN-LAST:event_groupsTableMouseClicked

    private void addStudentToGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToGroupButtonActionPerformed
        AddStudentToGroupDialog as = new AddStudentToGroupDialog(daycare, this);
        as.setLocationRelativeTo(null);
        as.setVisible(true);
    }//GEN-LAST:event_addStudentToGroupButtonActionPerformed
    public void postInit(DayCare daycare){
        classRoomSelect.setSelectedItem(null);
        selectGroupPanel.setVisible(false);
        groupInfoPanel.setVisible(false);
        setClassRoomDropDown(daycare.getClassRoomsList());
        classRoomSelect.setSelectedItem(null);
        groupDtm = (DefaultTableModel) groupsTable.getModel();
        studentDtm = (DefaultTableModel) studentTable.getModel();
        checkMaxLimitForGroup();
    }
    
    public void setClassRoomDropDown(List<Classroom> classRooms){
        int n = classRooms.size();
        System.out.println(n);
        String[] options = new String[n];
        for(int i = 0; i< n; i++){
            options[i] = (String) classRooms.get(i).getName();
        }
        classRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(options));
    }
            
    
    public static void handlePostClassroomCreate (JDialog jd){
        jd.dispose();
    }
    public static void handlePostStudentAddition (JDialog jd, int limit){
        jd.dispose();
        
    }
    
    public void checkMaxLimitForGroup(){
        if(selectedGroupIndex>=0){
        int sizeLimit = Integer.parseInt(noteValue.getText());
        int actualSize = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex()).getGroups().get(selectedGroupIndex).getStudentList().size();
        if(actualSize>=sizeLimit){
            addStudentToGroupButton.setVisible(false);
        }
        else{
            addStudentToGroupButton.setVisible(true);
        }
        }
    }
    
    public void checkMaxLimitForGroupAddition(){
        if(selectedClassIndex>=0){
            Classroom c = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex());
            boolean b = GroupRules.validate(c.getAgeLower(), c.getAgeHigher(), c.getGroups().size());
            addGroupButton.setVisible(b);
    }
    }  
    public void populateGroupTable(){
        Classroom c = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex());
        Vector<Group> groups = c.getGroups();
        int n = groups.size();
        String[] options = new String[n];
        groupDtm.setRowCount(0);
        
        for ( Group p : groups)
        {
         
             groupDtm.addRow(new Object[]{ p.getGroupName()});
        }
        groupsTable.setModel(groupDtm);
    }
    
    public void populateStudentTable(){
        studentTable.setVisible(false);
        Vector<Student> students = daycare.getClassRoomsList().get(selectedClassIndex).getGroups().get(selectedGroupIndex).getStudentList();
  
        int n = students.size();
        String[] options = new String[n];
        studentDtm.setRowCount(0);
        int x = 0;
        for ( Student p : students)
        {
         
             studentDtm.addRow(new Object[]{++x, p.getFirstName(), p.getLastName(), p.getAge(), p.getGpa()});
        }
        studentTable.setModel(studentDtm);
        studentTable.setVisible(true);
    }
    
    public void setTeacherName(){
        Teacher t = daycare.getClassRoomsList().get(selectedClassIndex).getGroups().get(selectedGroupIndex).getTeacher();
        teacherValueLabel.setText(""+t.getFirstName()+" "+t.getLastName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addStudentToGroupButton;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JComboBox<String> classRoomSelect;
    private javax.swing.JPanel groupInfoPanel;
    private javax.swing.JLabel groupLimitLabel;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JTable groupsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel notePrefix;
    private javax.swing.JLabel noteValue;
    private javax.swing.JPanel selectClassroomPanel;
    private javax.swing.JPanel selectGroupPanel;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel teacherHeadingLabel;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JLabel teacherValueLabel;
    private javax.swing.JLabel totalCount;
    // End of variables declaration//GEN-END:variables
}
